### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by HaNdTriX**
[clean-css](https://github.com/jakubpawlowicz/clean-css) has fixed a lot of bugs in since `v3.3.3`. It would be nice to have it updated.

### CODE REVIEW

**Comment by HaNdTriX** [comment]
The test failed but the sourcemaps seem to work. 

@murphydanger could you have a look at the [test](https://github.com/murphydanger/gulp-minify-css/blob/master/test/test.js#L123)? 

I do not think the Base64 VLQ Code changed because of this pull-request.

**Comment by murphydanger** [comment]
I won't be able to get to this until at least tonight (CET). Feel free to mess around with it until then.

**Comment by shinnn** [comment]
No thanks. https://github.com/murphydanger/gulp-minify-css/issues/111#issuecomment-115602333

**Comment by murphydanger** [comment]
@shinnn good catch. Sorry @HaNdTriX, gotta side with @shinnn here!

**Comment by shinnn** [comment]
Yeah, thanks for notifying us of source map changes though, @HaNdTriX :+1:

**Comment by HaNdTriX** [comment]
@shinnn sorry about that. Should have read the closed issues :flushed:

**Comment by mikew** [comment]
While using the caret definitely works, this now means that to "fix" builds on a CI server we have to locate the projects' `node_modules/` folder and remove `gulp-minify-css`, which is less then ideal, compared to bumping a minor version in our `package.js` and doing `git push`

**Pull request closed without merging**
